export const GET__STAKING__POOLS__PENDING = "GET__STAKING__POOLS__PENDING";
export const GET__STAKING__POOLS__SUCCESS = "GET__STAKING__POOLS__SUCCESS";
export const GET__STAKING__POOLS__FAILLED = "GET__STAKING__POOLS__FAILLED";
export const GET__USER__EARNING__PENDING = "GET__USER__EARNING_PENDING";
export const GET__USER__EARNING__SUCCESS = "GET__USER__EARNING_SUCCESS";
export const GET__USER__EARNING__FAILLED = "GET__USER__EARNING_FAILLED";
export const RESET_USER_STATE = "RESET_USER_STATE";
export const UPDATE__STAKING__POOLS = "UPDATE__STAKING__POOLS";
