export const GET__STAKING__POOLS = "GET__STAKING__POOLS"
export const GET__STAKING__POOLS__SUCCESS = "GET__STAKING__POOLS__SUCCESS"
export const GET__STAKING__POOLS__FAILLED = "GET__STAKING__POOLS__FAILLED"
export const SET__STAKING__POOL = "UPDATE__STAKING__POOL"